### ISSUE TITLE
doesn't work on github1s

### ISSUE THREAD

**Issue by HardwayLinka** [hypothesis/browser-extension#1020]
Can't do highlighting in [github1s](https://github1s.com/agentcooper/react-pdf-highlighter/blob/HEAD/src/types.ts#L12-L23)

![image](https://user-images.githubusercontent.com/45873697/199152489-12f5dd41-99f7-4f57-8629-881c3b8527ab.png)

**Comment by robertknight** [comment]
github1s presents code inside Visual Studio Code, which is a complex web application that is very different to a typical web page. As a general rule, Hypothesis does not support complex document viewers with custom rendering logic, except where we have implemented specific support for them (eg. PDF.js, VitalSource Bookshelf). For GitHub, you can however annotate in the regular code view, although I note there is currently an issue that GitHub's own styles override Hypothesis's highlighting.
