### ISSUE TITLE
Highlights disappear

### ISSUE THREAD

**Issue by SachinBhatia** [hypothesis/browser-extension#11]
https://drive.google.com/file/d/0B6uExxPqihrdMEpWTzNweXBZMDA/view

Take a look. Though both numbers are highlighted separately only one remains highlighted.

**Comment by i-aztec** [comment]
@SachinBhatia So how did you solve this problem?

**Comment by SachinBhatia** [comment]
@i-aztec I use Xodo for annotating pdfs as it fits my workflow better so I'm not aware if it has been solved.
