### ISSUE TITLE
[Feature Request] Always load plugin

### ISSUE THREAD

**Issue by solarkraft** [hypothesis/browser-extension#1152]
This is an extension of: https://github.com/hypothesis/browser-extension/issues/1123

It would be totally fine by me if the Hypothesis plugin was just always loaded into the page so that you can annotate right away (should of course be subject to a setting). It could be made less obtrusive by moving what is currently the sidebar into a popup that opens when you click the extension's button (or a hovering button).

**Comment by boehs** [comment]
duplicate of https://github.com/hypothesis/product-backlog/issues/1140

**Comment by solarkraft** [comment]
Sorry!
