### ISSUE TITLE
Remove client configuration from page when de-activating client

### ISSUE THREAD

**Issue by robertknight** [hypothesis/browser-extension#1180]
Deactivating the extension does not remove the `js-hypothesis-config` tag from the page. This results in an accumulation of these tags after unloading and re-loading the extension several times:

<img width="555" alt="js-hypothesis-config tags" src="https://user-images.githubusercontent.com/2458/230443862-791f50aa-86f9-43f3-85dd-3c9b58a424b7.png">

This creates some noise which is a bit annoying for debugging.  It may also cause confusion over which configuration is active. What happens is that the `parseJsonConfig` function in the client reads all of the `js-hypothesis-config` tags in order and merges them using `Object.assign`. This could in principle create a problem in future if the client was activated once with some configuration field `foo`, then de-activated, and later re-activated without `foo`. In that case the earlier `foo` would still apply.

When implementing this, we need to decide whether to remove all such tags from the page, or only ones injected by the current extension. Removing all tags would be the simplest. If the page has Hypothesis embedded, then removing all tags could also remove configuration that was originally added for the embedded client.

**Comment by acelaya** [comment]
I'm wondering if we could address this by making the extension add the `js-hypothesis-config` script with a `data-remove-on-unload` attribute.

As far as I can see on client, we have a [helper function](https://github.com/hypothesis/client/blob/f422054bccf8e518721f1c84bcbc73581d9f8ec3/src/annotator/hypothesis-injector.ts#L58) which removes all scripts with that attribute when unloaded.

I'm not sure if this "unload" would be triggered when the extension is deactivated, and also, if this function's purpose is different and perhaps a not super obvious approach from the browser extension perspective, but it's an idea.

**Comment by acelaya** [comment]
I have tested the `data-remove-on-unload` approach, and it works. Just in case we want to go that way.

**Comment by robertknight** [comment]
> I have tested the data-remove-on-unload approach, and it works. Just in case we want to go that way.

I had forgotten we had that. This is a nice simple solution and I think it will do what we need here.
