### ISSUE TITLE
Add option to save annotations to personal server

### ISSUE THREAD

**Issue by gobengo** [hypothesis/browser-extension#15]
Hey there. I really enjoy annotating with the Chrome Extension. I even think it's cool that other users in the hypothes.is network will see them.

But I also want to make sure that all my annotations are stored somewhere safe, someplace I can control and build programs around, like my personal server.

It would be super amazing if this extension included a configuration option where I could enter an additional URL to send my annotations too (e.g. in OA JSONLD format or a Web Annotation Protocol Container).

Just wondering, but is that type of feature within the realm of hypothes.is' mission? Helping me post annotations *outside* of the hypothes.is social network?

Regardless, I'd be willing to work on adding it, but I'm not intimately familiar with Annotator.js or Chrome Extensions. It would be an immensely helpful kickstart if someone who is familiar with those components could briefly explain how I could go about building this sort of thing. I imagine something like

MVP, build extra annotation server in at extension build-time:
* Hook into the Annotator.js used by this extension, and whenever an annotation is posted, call a callback defined by this extension. That callback will do some AJAX to the annotation server. *This is what I'd most like advice on.

After MVP, make the extra annotation server configurable in extension:
* [Chrome option](https://developer.chrome.com/extensions/optionsV2) for the API to hit with my annotation - I can probably rtfm on extensions and figure this out
* Read that value (from [chrome.storage](https://github.com/hypothesis/browser-extension/blob/master/src/client/app.html.mustache)?) instead of hardcoding it at build time.
* Remove "You must be logged in to create annotations.", which would not strictly be true any more.

**Comment by gobengo** [comment]
Maybe a rudimentary form of this could just be adding something like the following to embed.js.

```javascript
(async function () {
  const OTHER_ANNOTATION_SERVER = 'https://xyz'
  const annotator = await windowAnnotatorPresent()
  annotator.on('annotationCreated', async function (annotation) {
    const res = await fetch(OTHER_ANNOTATION_SERVER, {
      method: 'POST',
      headers: { 'content-type': 'application/json; charset=utf8' },
      body: toOpenAnnotation(annotation)
    })
  })
}())
onWindowAnnotator(annotator => annotator.on('annotationCreated', 
))
```

**Comment by gobengo** [comment]
In a related note, it's kind of a bummer that this extension doesn't work in a more 'open'/forkable way. That is, it's dependent on the opaque hypothes.is

**Comment by nickstenning** [comment]
Hi @gobengo! Making Hypothesis interoperable in the sense you describe, namely,

> It would be super amazing if this extension included a configuration option where I could enter an additional URL to send my annotations too (e.g. in OA JSONLD format or a Web Annotation Protocol Container).

is an important long-term goal of ours. We'll be making some changes in the coming months which will lay the groundwork for making the Hypothesis client (and hence the browser extension) able to talk to multiple annotation services.

I'm going to close this issue, as it would probably be better placed on the hypothesis/client repository, but also because we use issues for tracking bugs, but not for feature requests.

**Comment by gobengo** [comment]
ok
