### ISSUE TITLE
Could not load manifest

### ISSUE THREAD

**Issue by AntoniaWild** [hypothesis/browser-extension#176]
I am trying to build my own application based on hypothesis (editing only the client: https://h.readthedocs.io/projects/client/en/latest/developers/developing/#running-the-client-from-the-browser-extension) and therefore trying to load the (unchanged duplicate of the chrome) extension into Chrome: https://github.com/hypothesis/browser-extension/blob/master/docs/building.md.
The path of the file I am trying to load unpacked is ../browser-extension/src/chrome.
However, I get the error message "Manifest file is missing or unreadable. Could not load manifest." 
Do I need to transform the manifest.json.mustache file into a .json file?

**Comment by robertknight** [comment]
> Do I need to transform the manifest.json.mustache file into a .json file?

Yes. That file is a template which gets processed when you run `make` during the process of building the extension [as described in the README](https://github.com/hypothesis/browser-extension#development). The built extension is written to the `build` folder as `build/manifest.json`.

The `src/chrome` dir contains source files which are also processed as part of the build step.

**Comment by AntoniaWild** [comment]
Hi Robert, 
thanks for your help. As a newbie to programming I must have overseen this.
I am not trying to load the extension into Chrome, but always get the error message
"Unchecked runtime.lastError: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
Context
_generated_background_page.html
Stack Trace
_generated_background_page.html:0 (anonymous function)".
The application runs on port localhost:5000, which I have activated on my Router, but always displays connection error in Chrome. Do you know what could cause the issue?

**Comment by robertknight** [comment]
Hmm, I've not seen that before. What is the URL of the tab that you had active when you tried to activate the extension? Note. that activating extensions on tabs with "chrome://" URLs will always fail, as Chrome simply doesn't allow this.

**Comment by AntoniaWild** [comment]
Ok, so it seems to partially work on port 3000, though unpacking the Chrome extension always opens localhost:5000/welcome. Changed the port number in the manifest accordingly, catering to the port served when running ``make dev´´in the client directory. The local development version of hypothesis is taking very long to load and is missing the labels (see image attached).
![Screenshot 2019-07-01 at 18 31 47](https://user-images.githubusercontent.com/36530477/60452326-92fd1900-9c2e-11e9-84c7-a8e9702920d7.png)

**Comment by AntoniaWild** [comment]
Hi @robertknight,
sorry to bother you, but my browser extension set up for development is still not running properly. Fields are empty (see screenshot above) and in the developer console it states for "localhost:5000/api/:1": Error message: Failed to load resource: the server responded with a status of 404 (Not Found).

**Comment by robertknight** [comment]
I'm closing this issue as it is an old support request for help with building the extension locally.
