### ISSUE TITLE
don't cover page content

### ISSUE THREAD

**Issue by katrinleinweber** [hypothesis/browser-extension#19]
Hello :-)   The sidebar currently slides over the page content from the right. If the user can't simply shift page content to the left, annotation may be hindered because content is hidden. Please consider options like `sidebar placement: left | right` or `[ ] shift page content` (like side-by-side fullscreen view of two windows in macOS) to prevent content being hidden.

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/product-backlog/issues/94
