### ISSUE TITLE
Hypothesis fails to detect PDF in Chrome

### ISSUE THREAD

**Issue by robertknight** [hypothesis/browser-extension#212]
Tested by me with Chrome v78.0.3895.5 and @dwhly with Chrome 76.0.3809.132 on macOS.

**Steps to reproduce**

1. Install H Chrome extension
2. Go to http://researchoninnovation.org/patent.pdf
3. Click H icon to activate extension

**Expected result:** H loads the PDF in its custom PDF.js viewer, with the Hypothesis sidebar active
**Actual result:** The H sidebar appears in the native PDF viewer, as if the page were an HTML page. Since this is not our custom PDF.js viewer, annotation doesn't work.

Slack thread: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1567444151094900

**Technical notes**

Using Chrome dev tools with the extension's background page I've narrowed the issue down to the tab content type detection returning the wrong result ("HTML" instead of "PDF"). The browser extension detects the content type by running a script (the [`detectContentType`](https://github.com/hypothesis/browser-extension/blob/a95409f8422297592871af9c42a6bc3974528f94/src/common/detect-content-type.js#L29) function) in the context of the tab's top-level HTML document. 

In the Chrome context, it looks for an element matching the selector `embed[type="application/pdf"][name="plugin"]`.

When I looked at the actual HTML of the top-level frame in the PDF tab just now, the `embed` is present, but the `embed` does not have a `name` attribute:

<img width="394" alt="Screenshot 2019-09-02 23 15 50" src="https://user-images.githubusercontent.com/2458/64135041-673c1200-cddc-11e9-8816-1d059412b261.png">

I don't yet know the last Chrome version where this worked. My guess at the moment is that a recent change removed the `name` attribute.

**Comment by dwhly** [comment]
If this is correct, then (either now or shortly) PDF annotation will fail for all extension users.

**Comment by robertknight** [comment]
After some digging through the absolute awesomeness that is https://cs.chromium.org I found the place in the code that generates the top-level HTML for PDF tabs that we look for: https://cs.chromium.org/chromium/src/extensions/browser/guest_view/mime_handler_view/mime_handler_view_attach_helper.cc?type=cs&g=0&l=40. You can see that this HTML has no `name="plugin"` attribute on the `embed` element.

There is a code comment there that links to a Chrome tracking bug: https://bugs.chromium.org/p/chromium/issues/detail?id=659750.

Reading through the recent comments on that thread suggests that the Chrome team is currently switching over to a new implementation of PDF tabs behind a feature flag: https://bugs.chromium.org/p/chromium/issues/detail?id=659750#c79. It appears that the new implementation uses similar-but-slightly-different top level HTML for tabs displaying PDFs.

I checked that turning off the feature flag "MimeHandlerView in cross-process frame" under chrome://flags and restarting the browser works around the problem:

<img width="729" alt="Screenshot 2019-09-03 00 22 37" src="https://user-images.githubusercontent.com/2458/64135502-124eca80-cde1-11e9-9861-082d8616e6ef.png">
