### ISSUE TITLE
Docs should be improved to register extension with h/

### ISSUE THREAD

**Issue by LMS007** [hypothesis/browser-extension#217]
It's not clear that the browser extension needs it own oauth client registered in h. Both the docs and the readme files should make mention of this so its clear how to set up a custom client in a browser extension running on a local instance of h.

For example
`http://localhost:5000/admin/oauthclients`

![Screen Shot 2019-09-09 at 9 06 59 AM](https://user-images.githubusercontent.com/3939074/64547339-36c70d00-d2e1-11e9-8db6-5568a757532f.png)

Where  the redirect URL is the local unpacked browser extension loaded from the /build dir inside the browser extension repo (after you run `make`)

We should also make clear that the oauthClientId in the settings .json used when building the extension should point to this oauthclient. Namely, the Client Id returned when registering the new client in the h/ admin UI.

e.g.

```json
{
  "buildType": "dev",

  "apiUrl": "http://localhost:5000/api/",
  "authDomain": "localhost",
  "bouncerUrl": "http://localhost:8000/",
  "serviceUrl": "http://localhost:5000/",
  "websocketUrl": "ws://localhost:5001/ws",

  "googleAnalytics": "UA-26026798-6",

  "browserIsChrome": true,
  "appType": "chrome-extension",
  "oauthClientId": "6cf635cc-d318-11e9-bbf2-977360331651"
}
```

**Comment by lyzadanger** [comment]
I think we've nailed this now! Hope it's OK to close.
