### ISSUE TITLE
Is there a way to stay logged in longer in the Chrome Extension?

### ISSUE THREAD

**Issue by technoplato** [hypothesis/browser-extension#230]
I feel like I get logged out fairly quickly (perhaps one a day or two)

I would love if we could just stay logged in and not have to constantly log back in.

**Comment by robertknight** [comment]
You are most likely running into the issues with 3rd-party cookie blocking described in https://github.com/hypothesis/browser-extension/issues/484 or https://github.com/hypothesis/browser-extension/issues/313. I'm closing this as a duplicate of https://github.com/hypothesis/browser-extension/issues/484.
