### ISSUE TITLE
“Account settings” and “logout” menu items missing

### ISSUE THREAD

**Issue by fatbusinessman** [hypothesis/browser-extension#26]
**Steps to reproduce**

* Visit any page using the browser extension while logged into Hypothesis
* Open up the user menu

**Expected behavior**

* The four options in the menu are “[username]”, “Account settings”, “Help” and “Log out”

**Observed behavior**

* The “Account settings” and “Log out” items are missing

![The user menu, missing two of its items](https://cloud.githubusercontent.com/assets/32775/23218248/ae7c4892-f913-11e6-910c-63373a1f9498.png)

**Other notes**

This happens when using the browser extension, but doesn’t happen when using the embedded client or [via](https://via.hypothes.is).

**Comment by sheetaluk** [comment]
Fixed with https://chrome.google.com/webstore/detail/hypothesis-web-pdf-annota/bjfhmglciegochdpefhhlphglcehbmek

**Comment by dwhly** [comment]
Verified.  Thank you Sheetal!
