### ISSUE TITLE
Keyboard shortcuts for annotating and deleting an annotation

### ISSUE THREAD

**Issue by zhenlingcn** [hypothesis/browser-extension#270]
Annotating by mouse and deleting an annotation by mouse need much tedious effort, especially when I need to modify these annotations frequently. Keyboard shortcuts for annotating and deleting an annotation will significantly alleviate these problems. Therefore, is there any possible way to use keyboard shortcuts do these operations? Such as use "Alt+Q" for annotating selected text, and "Alt+E" for deleting the selected annotation.

**Comment by robertknight** [comment]
Thank-you for the feedback! We don't have much in the way of keyboard shortcuts for annotation tasks at the moment. We've been working on general keyboard accessibility recently so you can use the keyboard to navigate around the sidebar more easily. Providing convenient shortcuts for creating and editing annotations is something I think we should definitely look at. For PDFs we can chose something which we know doesn't conflict with the PDF viewer. For HTML documents I'm not sure what will be best.

If you have any more context about your particular use case, feel free to add it here.

**Comment by zhenlingcn** [comment]
Custom shortcuts are a good way.

**Comment by klemay** [comment]
Hey @zhenlingcn, we added a keyboard shortcut for annotating selected text last year: when the annotation adder pops up, type `a` to create an annotation or `h` to create a highlight. You can also navigate through and select text using your keyboard. [More info here](https://web.hypothes.is/help/creating-annotations-using-only-your-keyboard/)

I realize this partially addresses your request, as it doesn't cover modifying and deleting annotations. However, we have an issue that broadly covers keyboard shortcuts, so I am closing this in favor of https://github.com/hypothesis/product-backlog/issues/1202

**Comment by tedmiston** [comment]
@klemay I came across this issue while searching for a way to activate the Hypothesis browser extension with a keyboard shortcut.  I find that I switch to my mouse just to click the extension very very frequently, and think it would be much faster to have a custom shortcut, say `ctrl-h` to activate it.  Do you know if this is possible today?

**Comment by klemay** [comment]
I’m no longer at Hypothesis but I can tell you this is possible in Chrome!
You can set a keyboard shortcut to activate any Chrome extension— Google
has documentation for this.
