### ISSUE TITLE
Firefox Bookmarklet has stopped working on many websites

### ISSUE THREAD

**Issue by shivams** [hypothesis/browser-extension#290]
This morning, I found that the Firefox bookmarklet isn't working anymore on Github.com, Gmail.com, HackerNews and then some. I am using Firefox 72.0.2 (64-bit) on Ubuntu. I started Firefox in safe-mode also (hence all add-ons disabled), and yet it was the same. It continues to work for these sites on Chrome, however.

In the browser console, it was showing this warning:

`Loading failed for the <script> with source “https://cdn.hypothes.is/hypothesis/1.307.0/build/scripts/jquery.bundle.js?3746d4”.`

**Comment by robertknight** [comment]
The bookmarklet hasn’t worked on GitHub.com (and I would guess, gmail.com too) for a long time, due to security features (Content Security Policy) that the site uses. Until we release the Firefox extension, you can use the Chrome extension or https://via.hypothes.is
