### ISSUE TITLE
What cookies needs to be allowed to retain login

### ISSUE THREAD

**Issue by Pictor13** [hypothesis/browser-extension#313]
I disabled third-party cookies on Chrome, and then added `[*.]hypothes.is` into the **Allow** list, at [chrome://settings/content/cookies](chrome://settings/content/cookies).

But, still, every time I reload a page I loose the session and need to login again.

Is there some other domain that I should configure in order to have the Chrome extension to login automatically?

**Comment by jacrify** [comment]
Broken for me too on latest chrome mac os. Disabling third party cookies makes it work, however whitelisting the domain you quote above doesn't help me either.

**Comment by shuvashish76** [comment]
@Pictor13 as mentioned [here](https://groups.google.com/g/hypothesis-forum/c/cda3VUHSoqk/m/-7DvnGLNBAAJ) I allowed cookies from hypothesis id `[*.]bjfhmglciegochdpefhhlphglcehbme`
& its working for me...

**Comment by robertknight** [comment]
I'm closing this in favor of https://github.com/hypothesis/browser-extension/issues/484.
