### ISSUE TITLE
Privacy of my notes 

### ISSUE THREAD

**Issue by Gahamelas** [hypothesis/browser-extension#348]
I understood from reading the instructions, that there was no way to make my annotations private.
But I think that by creating my own group, and just posting to it, would make all my activity private. Is this correct? What I am not sure about is that the group is visible to others (not its content), so they can join without my approval (if I understand correctly). Thanks for clarifying this in advance.

**Comment by robertknight** [comment]
> I understood from reading the instructions, that there was no way to make my annotations private.

When you create an annotation you can choose whether to share it with the rest of the group or make it private. Click the drop-down arrow next to the "Post to ..." button in the comment entry box.

Separate to that, you can also create private groups whose annotations are only visible to members. If you are the only member of the group then the content is effectively private. A caveat is that anyone with the URL of the group can join it, so the group only remains private as long as you don't share the URL.

Does this answer your question?

**Comment by Gahamelas** [comment]
Yes, that answers to the questions. Thank you! Except for one thing: Highlights are by default public no matter what?

**Comment by robertknight** [comment]
It is the other way around - highlights are _private_ by default and you need to add a tag or comment before you can (optionally) share it with other members of the group. This is because a highlight on its own doesn't have much value for anyone else.
