### ISSUE TITLE
Reduce the number of badge API requests sent

### ISSUE THREAD

**Issue by seanh** [hypothesis/browser-extension#396]
Ideas:

* Have a client-side blocklist of URL patterns or domains that we don't send badge requests for (current [server-side blocklist](https://github.com/hypothesis/h/blob/71cb4949ab8f850c9daa4c157362b562388d8140/h/views/badge.py#L28))
* Don't send the badge request for a newly-navigated URL until the user stays on that URL for a couple of seconds
* Have rate limiting for how quickly badge requests will be sent, no matter what
* Don't send requests if the URL for a tab changes from URL A to URL B where both URLs are the same as far as the backend is concerned. For example, if they only differ by fragment or scheme (HTTP vs HTTPS)

But really, just do whatever works. The aim is to significantly reduce the number of badge API requests being sent, while keeping the user experience good enough.

**Comment by lyzadanger** [comment]
> Have a client-side blocklist of URL patterns or domains that we don't send badge requests for

This step is complete.

**Comment by esanzgar** [comment]
Regarding point #4 (request badge count only if A and B are different URLs [ignoring fragment]): I experimented a little bit with that.

In order to implement that, we must keep the current URL but **only for certain amount of time**. The reason been that a page reload by the user, should genuinely request an updated badge count.

In my opinion, this may confuse users.

**Comment by esanzgar** [comment]
Another source of confusion is that the badge count can sometimes be different to the number of annotations in the page. This is cause by document equivalence. For example, if the document contains a DOI, the number of annotations by the client returned is not only based on URL.

Ideally, both, the number reported by the badge (browser-extension) and in the client should be the same. 

I know this may be difficult to achieve but it would be the ideal scenario.

**Comment by robertknight** [comment]
A first PR which makes improvements here has been shipped. https://github.com/hypothesis/browser-extension/pull/409 debounces/defers updates to reduce the number of requests when a browser tab is updated frequently. There are some early data here which show that the number of requests to the service appears to have been halved at 14:00-14:30 today compared with the same time period yesterday: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1604414564020000. We'll need to keep observing to get a better confirmation.

**Comment by esanzgar** [comment]
On a second PR, we implemented a cross-tab cache to further reduce the number of requests #424.
