### ISSUE TITLE
Chrome extension "Allow access to file URLs" error page is out-of-date

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/browser-extension#416]
The instructions presented in the Chrome extension error page to enable access to file URLs are out of date for the current versions of Chrome.
<img width="1079" alt="Screen Shot 2020-10-08 at 1 19 26 PM" src="https://user-images.githubusercontent.com/71603629/95492883-b5213300-0969-11eb-8c25-a8b13a759324.png">
**To Reproduce:**

1. Make sure "Allow access to file URLs" is turned off in Chrome H extension
2. Open local PDF in Chrome
3. Activate H extension
4. Error page with out-of-date instructions loads

**Comment by klemay** [comment]
We might consider pointing users to https://web.hypothes.is/help/annotating-locally-saved-pdfs/#2-change-your-settings-in-chrome-if-applicable

and keeping the KB article up-to-date. I will work with Matt to get the KB portion of this fixed!

**Comment by lyzadanger** [comment]
@klemay and all—let's aim to keep the messaging in the extension itself as minimal and "evergreen" as possible, and link to a KB article that can more easily be kept up-to-date, yes.

**Comment by klemay** [comment]
The KB article needed a small update, which I have completed!
