### ISSUE TITLE
Rapid change of annotation number in the badge

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/browser-extension#433]
In pages that take a while to load (for example [this](https://docs.google.com/presentation/d/1R2zbiu5h1-vNcUws3zP-gebW6xdgQT7kdg6vUizD3uw/edit?pli=1#slide=id.g8a740aae2c_0_10)), I have noticed that the annotation count in the badge changes during the loading of the page.

This is an example:

![Screen Recording 2020-11-09 at 11 56 01](https://user-images.githubusercontent.com/8555781/98654806-10ff2300-233f-11eb-8053-753804318299.gif)

This is caused by `annotationCount` been reset to zero during the loading.

**Comment by esanzgar** [comment]
We need a way to identify the first callback fired from the [onTabUpdate](https://developer.chrome.com/extensions/tabs#event-onUpdated) event in order to reset the counter.

I have tried two approaches unsuccessfully:
* reset the count on [tabStatus](https://developer.chrome.com/extensions/tabs#type-TabStatus) `=== 'unloaded'`
* detect when [tab.pendingUrl is defined](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/5zu_PT0arls)

I feel that if we were able to hook to the lifecycle of the page we would be able to not only reset a the right time the counter, but fetch the badge only once.

**Comment by lyzadanger** [comment]
A note (cc @klemay) that I'm removing this from the "To Review" column in the bug backlog as it looks like a fix will land imminently.
