### ISSUE TITLE
Thrown Raven TypeError in extension background page console

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/browser-extension#434]
I have seen the following error in the console in the production browser-extension:

```
extension.bundle.js:5213 Uncaught TypeError: Raven.config is not a function
    at Object.init (extension.bundle.js:5213)
    at Object.20../hypothesis-chrome-extension (extension.bundle.js:5055)
    at o (extension.bundle.js:1)
    at r (extension.bundle.js:1)
    at extension.bundle.js:1
```

**Comment by lyzadanger** [comment]
@esanzgar Hi! I think more information is needed here. What causes this error to happen? When does it happen? Does it happen in the current-tab console, or is it in the extension's own console? I've not seen it before...

**Comment by esanzgar** [comment]
This error is displayed on the console when inspecting the `background page`.
