### ISSUE TITLE
Option for hypothesis extension as always active

### ISSUE THREAD

**Issue by shuvashish76** [hypothesis/browser-extension#470]
option in settings as "always active" so that the Annotation sidebar can be visible in all websites & user don't have to activate it manually each time.

**Comment by Elinpf** [comment]
Hasn't this feature been added yet?

**Comment by klemay** [comment]
@Elinpf and @shuvashish76 this has not been added yet, but your comment reminds me that we are tracking this issue in our product backlog: https://github.com/hypothesis/product-backlog/issues/1140

I am closing this issue in favor of the other one.
