### ISSUE TITLE
If PDF.js places page to left rather than centered there'd be more space for hypothesis

### ISSUE THREAD

**Issue by imurray** [hypothesis/browser-extension#55]
The PDF.js widget places the rendered pdf page in the middle of the browser window, but isn't aware of the hypothesis sidebar. If instead the page was placed as far left as it could go, there would be more room for the hypothesis sidebar, and it would be less likely to overlap the page content.

I realize maintaining a more invasive patch to PDF.js might be a pain. This enhancement would be a nice-to-have, if it isn't too difficult. Presumably the change would also benefit the viewer that the hypothesis web client includes, wherever it gets it from.

**Comment by robertknight** [comment]
We have implemented a feature called "side-by-side" mode in Hypothesis where the PDF content is shifted left and displayed alongside the sidebar when open, as long as the window is wide enough to reasonably accommodate the content and the sidebar.

**Comment by imurray** [comment]
Thank you very much! This new feature works great on desktop for me under usual circumstances. It's a huge improvement!

Nitpick:

> as long as the window is wide enough to reasonably accommodate the content and the sidebar.

There's a choice here that makes the experience strange for me. As I widen the sidebar, the PDF page moves to the left until it hits the left margin (great!). But then at some point, when the side bar is really wide, the PDF page jumps to the right again. Even if I can't see the whole page, it would be better to have it stay on the left, so I can see as much of it as possible.

On a landscape phone view (firefox for android) I can't get the PDF page to move to the left at all, even if I zoom out enough for there to be room to see the page and the sidebar at the same time.

If the page and sidebar overlap, I'm not seeing why we wouldn't always want to move the page to the left, to reduce that overlap as much as possible.
