### ISSUE TITLE
annotations didn't appear

### ISSUE THREAD

**Issue by redstoneleo** [hypothesis/browser-extension#558]
My annotations were created on 11 Sep 2020 for 
https://docs.djangoproject.com/en/3.1/intro/tutorial04/
but they didn't appear in my Chrome 86 on Win7 64bit anymore. 
Invite url of annotations in the page : https://hypothes.is/groups/pjPikEvR/my-annotation 
After some investigation, I found the urls in the following two parts are different , so is this the cause of the issue?
![image](https://user-images.githubusercontent.com/5896180/117537392-24abed80-b033-11eb-9feb-6522e0a4634f.png)

Browser extension status :
![image](https://user-images.githubusercontent.com/5896180/117537607-ac462c00-b034-11eb-8dcd-9d2d9312928f.png)

**Comment by klemay** [comment]
Hi @redstoneleo, please email support@hypothes.is for help!
