### ISSUE TITLE
Client side routing 

### ISSUE THREAD

**Issue by saheedoladele-outlier** [hypothesis/browser-extension#603]
Does this work with client-side routing? I couldn't find much info in regards to that. Thanks in advance!

**Comment by robertknight** [comment]
Hello. The short answer is that client-side routing is not handled currently by the Hypothesis client.

The longer answer is that when you create an annotation, Hypothesis will correctly capture the current URL and document metadata even if client-side navigations have happened. However it does not detect when client-side navigations have happened and update the set of loaded annotations accordingly. As a result you'll continue to see annotations from whatever page was active when the client was initially loaded.

See also https://github.com/hypothesis/product-backlog/issues/1135.

**Comment by robertknight** [comment]
Closing this as https://github.com/hypothesis/product-backlog/issues/1135 has been resolved.
