### ISSUE TITLE
Problem running make 

### ISSUE THREAD

**Issue by wefahakem** [hypothesis/browser-extension#62]
I'm trying to build the project but I have a problem running the command make on the problem. I have this log : 
node_modules/.bin/browserify -t babelify -d src/common/ex
es/.bin/exorcist build/extension.bundle.js.map >build/ext
'node_modules' not recognized as an internal or external command
make: *** [build/extension.bundle.js] Erreur 255

Can anyone help?

**Comment by robertknight** [comment]
Did you run `npm install` before running `make`?

**Comment by wefahakem** [comment]
Yes I did, and the node_modules exists

**Comment by robertknight** [comment]
Ah - are you running this command on Windows? If so, what version of make are you using?

**Comment by wefahakem** [comment]
Yes, I'm running it on Windows, I'm using make-3.81, should I downgrade it?

**Comment by robertknight** [comment]
Whose version of _make_ is it though (ie. where did you install it from)? nmake? GNU Make?

It might suffice to change the lines at the top of the Makefile by modifying the search path for binaries instead of using relative paths to the various tools that it runs, like so:

```
SETTINGS_FILE := settings/chrome-dev.json
PATH := node_modules/.bin:$(PATH)

BROWSERIFY := browserify
ESLINT := eslint
EXORCIST := exorcist
MUSTACHE := mustache
```

Can you give that a try and let me know if it works. @judell I believe you've built the browser extension on Windows? Did you have to make any changes to get it to work?

**Comment by wefahakem** [comment]
I'm using GNU Make, but I get the same issue from nmake. I made the modification that you suggested, it worked for the first. Thanks a lot :) . But the build is not complete yet . It is blocking in tools command. Can you or @judell  provide me with the Windows Makefile version If you have worked on it. Thanks in advance.

**Comment by robertknight** [comment]
>  But the build is not complete yet . It is blocking in tools command.

Can you clarify what you mean?

**Comment by wefahakem** [comment]
I'm getting this error : 'tools' not recognized as an internal or external command
make: *** [build/.settings.json] Erreur 255.

**Comment by robertknight** [comment]
Ah right, that will be a variation of the same problem. I have a few meetings this afternoon but if you have a look through the Makefile you should be able to resolve the issue in a similar way to the above by adding "tools" to `PATH` in the Makefile. Alternatively changing the invocation from `tools/some-script.js` to `node tools/some-script.js` should also work.

**Comment by wefahakem** [comment]
Thanks, it works with the changes that you suggested :)

**Comment by judell** [comment]
I'm late to this party but, @robertknight, no, I studiously avoid trying to build open source software on Windows. Just too many headaches. I do everything in Linux VMs. Thanks for getting @wefahakem unblocked, though!

**Comment by lyzadanger** [comment]
This has been resolved!
