### ISSUE TITLE
User testing sessions with assistive technology users

### ISSUE THREAD

**Issue by klemay** [hypothesis/browser-extension#63]
- [x] Complete test session with JAWS user
- [x] Share meeting recording with team
- [x] Synthesize notes; break up recording into smaller videos
- [x] Create list of development tasks that will make h screen-reader compliant

**Comment by klemay** [comment]
Link to whole video is here: https://hypothes-is.slack.com/files/U8D0XFS72/F9CQ57JNN/george_jaws.mp4

(Katelyn will provide smaller chunks of this for review)

**Comment by klemay** [comment]
See https://hypothes-is.slack.com/archives/C8TPC8XMK/p1520012586000123 for timeline notes as well as main takeaways.

**Comment by ajpeddakotla** [comment]
Closing this as it is completed.
