### ISSUE TITLE
Update development docs to include OAuth client registration

### ISSUE THREAD

**Issue by robertknight** [hypothesis/browser-extension#64]
The development docs for [building the extension](https://github.com/hypothesis/browser-extension/blob/master/docs/building.md) for development do not mention anything about registering an OAuth client, which is now a mandatory step.

**Comment by lyzadanger** [comment]
@robertknight Is this issue still valid? It seems to me that the docs _do_ talk about this on this page: https://h-client.readthedocs.io/en/latest/developers/developing/#setting-up-a-client-development-environment

**Comment by lyzadanger** [comment]
This has been rectified.
