### ISSUE TITLE
1.69.0.0: https://10.241.109.147:5000/welcome connection timeout

### ISSUE THREAD

**Issue by grahamperrin** [hypothesis/browser-extension#67]
1. https://addons.mozilla.org/addon/annotons-nos-contenus/
2. install version 1.69.0.0

## Result

3. in a new tab, https://10.241.109.147:5000/welcome times out.

## Test environments

- [Waterfox](https://github.com/MrAlex94/Waterfox/) 56.1.0_7
- Firefox 59.0.2_4,1

– both on FreeBSD-CURRENT.

**Comment by robertknight** [comment]
This add-on is not maintained or supported by Hypothesis, although it looks like it may be a repackaged version of our code. Please contact the add-on's author for support.

**Comment by grahamperrin** [comment]
Apologies. https://web.archive.org/web/20180413125239/https://addons.mozilla.org/en-GB/firefox/addon/annotons-nos-contenus/reviews/1102021/

> Misleading; https://hypothes.is/ is not the home page for the add-on, it's the home page for the service. 

![2018-04-13 13 55 36 add-ons manager](https://user-images.githubusercontent.com/192271/38735991-6f547468-3f22-11e8-8335-f16ef613963b.png)

**Comment by robertknight** [comment]
Thanks for the info. We do still intend to ship an officially supported Firefox extension. The author of this extension is welcome to use our open source code, but we should ask them to make it clear that this isn't an "official product" of the Hypothesis project.
