### ISSUE TITLE
1.81.0.0: Uncaught ReferenceError: annotator is not defined

### ISSUE THREAD

**Issue by lkraav** [hypothesis/browser-extension#69]
(Chrome 66, Linux)

Majority of the functionality seems to work, but sidebar numbered tabs are failing to trigger opening the sidebar. Stack trace:

```
bucket-bar.coffee:1 Uncaught ReferenceError: annotator is not defined
    at HTMLDivElement.<anonymous> (bucket-bar.coffee:1)
    at HTMLDivElement.dispatch (jquery.slim.js:5206)
    at HTMLDivElement.v.handle (jquery.slim.js:5014)
(anonymous) @ bucket-bar.coffee:1
dispatch @ jquery.slim.js:5206
v.handle @ jquery.slim.js:5014
```

It seems like https://github.com/openannotation/annotator/issues/615 has been working on it on client side, but as we seem to be shipping our own jQuery here, why would this error occur?

**Comment by lkraav** [comment]
Oh, it's actually this https://github.com/hypothesis/client/issues/562

**Comment by robertknight** [comment]
Closing as a duplicate.
