### ISSUE TITLE
The extension causes Chrome browser to become unresponsive

### ISSUE THREAD

**Issue by benwoodward** [hypothesis/browser-extension#704]
If I install 1.896.0.0 from Chrome store, the extension crashes the browser the moment I activate the extension. I've installed 1.906.0.0 from master and the extension works for a while, but after a few minutes the browser becomes unresponsive. How do I debug this?

**Comment by robertknight** [comment]
What is the exact version of Chrome you are using, as shown at the top of chrome://version/ ? Does it make a difference what web page or PDF you are viewing when you activate the extension (for example try: https://example.com, a PDF, a page that is part of the Chrome UI such as chrome://settings)?

**Comment by br1ttle** [comment]
Experiencing the same bug on Brave Browser. Running Monterey 12.0 and Brave Browser Beta 1.34.64.

**Comment by robertknight** [comment]
@br1ttle - I'm going to close this issue as there wasn't a response to the initial reply. Your problem may be entirely unrelated (different browser, possibly different OS, other factors), however the debugging steps I posted in that comment are still relevant, so I suggest to try those and report what happens.
