### ISSUE TITLE
Building extension for publishing on chrome store

### ISSUE THREAD

**Issue by AnnajiAmarnath** [hypothesis/browser-extension#74]
Do we need any changes  in make , gulp .. files to create extension which can be published on chrome store. Google Chrome Web Store team  rejected as the submitted extension contain minified or obfuscated code which is not human readable.  An example of one such file in your package is content/build/pdf.worker.js,content/web/compatibility.js.

**Comment by robertknight** [comment]
Hello @AnnajiAmarnath,

Do you have the exact rejection notice from the Chrome Web Store Team and can you also upload a copy of the contents of the `build/` directory that you are trying to submit?

We have been submitting our extension with those files included without problems. Our builds do not minify the code at all. They just run `make SETTINGS_FILE=settings/chrome-prod.json`, and then use Chrome Web Store APIs to submit the zip file.

We haven't published a new version in a few weeks so it is possible there have been some recent rule changes.
