### ISSUE TITLE
Browser-extension api changes from hypothesis server api to localhost

### ISSUE THREAD

**Issue by chinmaygghag** [hypothesis/browser-extension#75]
I wanted to make changes to browser extension to point to my local system (server) is there any document which can point me to it?

I see there in app.html apiUrl points to "https://hypothes.is/api/" & as per the h documentation, h runs at port 5000 so what exact changes should be made?

**Comment by raphael10-collab** [comment]
@chinmaygghag 

As said here: https://github.com/hypothesis/browser-extension/issues/956#issue-1361227928 I do not understand either what should I do in order to create an OAuthClient (http://localhost:5000/admin/oauthclients) for the browser-extension to use it in my local running instance of h
