### ISSUE TITLE
Add option to move the popup to the top of selected text

### ISSUE THREAD

**Issue by caoyirui** [hypothesis/browser-extension#929]
What the title says, and if not, can you tell me which file I need to modify so i can build the extension myself.

**Comment by robertknight** [comment]
The Annotate/Highlight toolbar pops up where it does to avoid a conflict with the native text selection popups on mobile. If you want to change it, you'll need to first check out the Hypothesis client and modify the [adder.js](https://github.com/hypothesis/client/blob/main/src/annotator/adder.js) file, then build a version of the browser extension using the modified client.
